export const ADD_BUTTON = 'FILTER/BUTTONS/ADD-BUTTON';
export const APPLY_BUTTON = 'FILTER/BUTTONS/APPLY-BUTTON';
export const DELETE_BUTTON = 'FILTER/BUTTONS/DELETE-BUTTON';
export const CLEAR_BUTTON = 'FILTER/BUTTONS/CLEAR-BUTTON';
